apache2:
  nameOverride: b-apache
  replicaCount: 2
  image:
    name: bitnami/apache
    tag: latest
  ports:
     - name: http
       containerPort: 8081
       protocol: TCP
  route:
    enabled: true
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8081
  route:
    enabled: true
  env:
     - name: APACHE_HTTP_PORT_NUMBER
       value: "8081"
  resources:
    limits:
      cpu: 250m
      memory: 400Mi
kubeapps:
  nameOverride: b-kubeapps
  replicaCount: 1
  image:
    name: bitnami/kubeapps-dashboard
    tag: latest
  route:
    enabled: true
  resources:
    limits:
      cpu: 250m
      memory: 400Mi
webapp-color:
  nameOverride: b-webapp-color
  image:
    name: kodekloud/webapp-color
    tag: latest
  env:
  - name: APP_COLOR
    value: darkblue
  resources:
    limits:
      cpu: 250m
      memory: 400Mi
  route:
    enabled: true
