apache2:
  replicaCount: 3
  image:
    name: bitnami/apache
    tag: latest
  ports:
     - name: http
       containerPort: 8081
       protocol: TCP
  route:
    enabled: true
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8081
  route:
    enabled: true
  env:
     - name: APACHE_HTTP_PORT_NUMBER
       value: "8081"
  resources:
    limits:
      cpu: 250m
      memory: 400Mi
nginx:
  replicaCount: 1
  image:
    name: bitnami/nginx
    tag: latest
  route:
    enabled: true
  env:
     - name: EXAMPLE_ENV
       value: "blubb"
  resources:
    limits:
      cpu: 250m
      memory: 400Mi
kubeapps:
  replicaCount: 1
  image:
    name: bitnami/kubeapps-dashboard
    tag: latest
  route:
    enabled: true
  resources:
    limits:
      cpu: 250m
      memory: 400Mi
golang-example:
  replicaCount: 1
  image:
    name: fhochleitner/runtime-go-application
    tag: latest
  route:
    enabled: true
webapp-color:
  image:
    name: kodekloud/webapp-color
    tag: latest
  env:
  - name: APP_COLOR
    value: darkblue
  resources:
    limits:
      cpu: 250m
      memory: 400Mi
  route:
    enabled: true