apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: erhard-apache-sample-application
spec:
  destination:
    namespace: erhard-pg
    server: https://kubernetes.default.svc
  source:
    path: apache-sample
    repoURL: https://github.com/ErhardSiegl/bke-runtime-showcase
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
