apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: showcase-project
  namespace: felix-playground
spec:
  roles:
  # A role which provides read-only access to all applications in the project
  - name: read-only
    description: Read-only privileges to showcase-project
    policies:
    - p, proj:showcase-project:read-only, applications, get, showcase-project/*, allow
    groups:
    - Gepardec
  - name: full-access
    description: full-access privileges to showcase-project
    policies:
    - p, proj:showcase-project:*, applications, *, showcase-project/*, allow
    groups:
    - Gepaplexx
  sourceRepos:
  - 'https://github.com/fhochleitner/*'
  destinations:
  - namespace: 'felix-playground'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'