gp-bke-runtime-minimal-application:
  replicaCount: 2
  image:
    name: bitnami/apache
    tag: latest
  ports:
     - name: http
       containerPort: 8081
       protocol: TCP
  route:
    enabled: true
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8081
  route:
    enabled: true
    tls:
      enabled: true
      termination: edge
  env:
     - name: APACHE_HTTP_PORT_NUMBER
       value: "8081"
  resources:
    limits:
      cpu: 250m
      memory: 400Mi