gp-bke-runtime-minimal-application:
  replicaCount: 2
  image:
    name: bitnami/apache
    tag: latest
  ports:
     - name: http
       containerPort: 80
       protocol: TCP
  route:
    enabled: true
  service:
    type: ClusterIP
    port: 8080
    targetPort: 80
  route:
    enabled: true
  env:
     - name: APACHE_HTTP_PORT_NUMBER
       value: "80"
  resources:
    limits:
      cpu: 250m
      memory: 400Mi